// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
// Example 3:

// Input: s = "a", t = "aa"
// Output: "a"

class Solution {
    public char findTheDifference(String s, String t) {
        List<Character> list = new ArrayList<>();
        for(char c: t.toCharArray()){
           list.add(c); 
        }
        for(char c: s.toCharArray()){
           list.remove(list.indexOf(c)); 
        }
        return list.get(0);
    }
}
